"""
chimera-runtime — Configuration Manager

Loads, validates, and saves .chimera/config.yaml.
Supports environment variable overrides for sensitive values (API keys).

Config resolution order:
  1. YAML file values
  2. Environment variable overrides (CHIMERA_API_KEY, CHIMERA_MODEL, etc.)
  3. Defaults from AgentConfig dataclass
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Dict, Optional

import yaml

from .models import (
    AgentConfig,
    AgentMetaConfig,
    LLMConfig,
    PolicyConfig,
    AuditConfig,
    OversightConfig,
    CausalConfig,
)


# ============================================================================
# DEFAULTS
# ============================================================================

DEFAULT_CONFIG_DIR = ".chimera"
DEFAULT_CONFIG_FILE = "config.yaml"
DEFAULT_CONFIG_PATH = os.path.join(DEFAULT_CONFIG_DIR, DEFAULT_CONFIG_FILE)

# Environment variable mappings
ENV_OVERRIDES = {
    "CHIMERA_API_KEY": ("llm", "api_key"),
    "CHIMERA_MODEL": ("llm", "model"),
    "CHIMERA_PROVIDER": ("llm", "provider"),
    "CHIMERA_POLICY_FILE": ("policy", "file"),
    "CHIMERA_AUDIT_DIR": ("audit", "output_dir"),
}


# ============================================================================
# ERRORS
# ============================================================================

class ConfigError(Exception):
    """Raised when configuration is invalid or cannot be loaded."""
    pass


# ============================================================================
# CORE FUNCTIONS
# ============================================================================

def load_config(path: Optional[str] = None) -> AgentConfig:
    """
    Load agent configuration from YAML file with env var overrides.

    Resolution order:
      1. Read YAML file (or use defaults if file doesn't exist)
      2. Apply environment variable overrides
      3. Validate the final configuration

    Args:
        path: Path to config YAML. Defaults to .chimera/config.yaml

    Returns:
        Validated AgentConfig

    Raises:
        ConfigError: If the config file exists but is malformed,
                     or if validation fails
    """
    config_path = Path(path) if path else Path(DEFAULT_CONFIG_PATH)

    # Load YAML or start with empty dict
    raw: Dict[str, Any] = {}
    if config_path.exists():
        try:
            with open(config_path, "r", encoding="utf-8") as f:
                content = f.read()
                if content.strip():
                    raw = yaml.safe_load(content) or {}
        except yaml.YAMLError as e:
            raise ConfigError(f"Failed to parse config at {config_path}: {e}")
        except OSError as e:
            raise ConfigError(f"Failed to read config at {config_path}: {e}")

    if not isinstance(raw, dict):
        raise ConfigError(
            f"Config file must contain a YAML mapping, got {type(raw).__name__}"
        )

    # Apply environment variable overrides
    raw = _apply_env_overrides(raw)

    # Parse into AgentConfig
    config = AgentConfig.from_dict(raw)

    # Validate
    validate_config(config)

    return config


def save_config(config: AgentConfig, path: Optional[str] = None) -> Path:
    """
    Save agent configuration to YAML file.

    Creates parent directories if they don't exist.
    Never writes api_key to disk (security).

    Args:
        config: AgentConfig to save
        path: Output path. Defaults to .chimera/config.yaml

    Returns:
        Path to the written config file
    """
    config_path = Path(path) if path else Path(DEFAULT_CONFIG_PATH)
    config_path.parent.mkdir(parents=True, exist_ok=True)

    data = config.to_dict()

    yaml_content = yaml.dump(
        data,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
        width=120,
    )

    header = (
        "# chimera-runtime configuration\n"
        "# Generated by: chimera-runtime init\n"
        "# Docs: https://github.com/Chimera-Protocol/project-chimera\n"
        "#\n"
        "# API keys should be set via environment variables:\n"
        "#   export CHIMERA_API_KEY=sk-...\n"
        "#\n\n"
    )

    with open(config_path, "w", encoding="utf-8") as f:
        f.write(header + yaml_content)

    return config_path


def validate_config(config: AgentConfig) -> None:
    """
    Validate agent configuration for completeness and correctness.

    Raises:
        ConfigError: If any validation rule fails
    """
    errors: list[str] = []

    # LLM validation
    valid_providers = {"openai", "anthropic", "google", "ollama"}
    if config.llm.provider not in valid_providers:
        errors.append(
            f"llm.provider must be one of {valid_providers}, "
            f"got '{config.llm.provider}'"
        )

    if not (0.0 <= config.llm.temperature <= 2.0):
        errors.append(
            f"llm.temperature must be between 0.0 and 2.0, "
            f"got {config.llm.temperature}"
        )

    if config.llm.max_retries < 1:
        errors.append(
            f"llm.max_retries must be >= 1, got {config.llm.max_retries}"
        )

    if config.llm.candidates_per_attempt < 1:
        errors.append(
            f"llm.candidates_per_attempt must be >= 1, "
            f"got {config.llm.candidates_per_attempt}"
        )

    # Policy validation
    if not config.policy.file:
        errors.append("policy.file must not be empty")

    # Audit validation
    valid_formats = {"json", "compact", "both"}
    if config.audit.format not in valid_formats:
        errors.append(
            f"audit.format must be one of {valid_formats}, "
            f"got '{config.audit.format}'"
        )

    if config.audit.retention_days < 1:
        errors.append(
            f"audit.retention_days must be >= 1, "
            f"got {config.audit.retention_days}"
        )

    # Oversight validation
    if config.oversight.stop_on_consecutive_blocks < 1:
        errors.append(
            f"oversight.stop_on_consecutive_blocks must be >= 1, "
            f"got {config.oversight.stop_on_consecutive_blocks}"
        )

    if errors:
        msg = "Configuration validation failed:\n" + "\n".join(
            f"  - {e}" for e in errors
        )
        raise ConfigError(msg)


# ============================================================================
# INTERNAL HELPERS
# ============================================================================

def _apply_env_overrides(raw: Dict[str, Any]) -> Dict[str, Any]:
    """
    Apply environment variable overrides to raw config dict.
    Only applied if the env var is set and non-empty.
    """
    for env_var, (section, key) in ENV_OVERRIDES.items():
        value = os.environ.get(env_var)
        if value:
            if section not in raw:
                raw[section] = {}
            raw[section][key] = value
    return raw
